services:

  mongo:
    image: mongo:8
    container_name: bookstore-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./server
    container_name: bookstore-backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URL: mongodb://mongo:27017/bookstore
    depends_on:
      - mongo

  frontend:
    build: ./client
    container_name: bookstore-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data: